apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wh2pg
  namespace: argocd
spec:
  destination:
    namespace: wh2pg
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  sources:
    # Chart Helm depuis OCI registry (GHCR)
    - chart: wh2pg
      repoURL: oci://ghcr.io/jzacharie/charts
      targetRevision: '*'  # Utilise la dernière version
      helm:
        valueFiles:
          - $values/values/wh2pg/values.yaml
    # Repository Git pour les values personnalisés
    - ref: values
      repoURL: git@github.com:JZacharie/jo3.git
      targetRevision: main
